POST http://localhost:8080/login
Content-Length: application/json

{
    "username": "user1",
    "password": "password1"
}
###

GET http://localhost:8080/users?id=3vhwj9b6j31
Authorization: qwv4tvbwnol
###

GET http://localhost:8080/users?name=miko
Authorization: viqzj7ojqzp
###

PuT http://localhost:8080/users
Authorization: viqzj7ojqzp
Content-Length: application/json

{
    "age": 45,
    "name": "mikosky",
    "email": "mikosky@mike.com",
    "workPosition": 3
}
###

DELETE http://localhost:8080/users?id=3vhwj9b6j31
Authorization: qwv4tvbwnol
###